// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ7g2BuxHXi0Pn7S_IQpNEJVG8Kih65JQ',
    appId: '1:579029137093:web:52ea948027df3e97b762ac',
    messagingSenderId: '579029137093',
    projectId: 'myinsta-b4476',
    authDomain: 'myinsta-b4476.firebaseapp.com',
    storageBucket: 'myinsta-b4476.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOGVjiKnH9L9IKStGaeoWKdC7xeATdn2Q',
    appId: '1:579029137093:android:3bee57452c96e7deb762ac',
    messagingSenderId: '579029137093',
    projectId: 'myinsta-b4476',
    storageBucket: 'myinsta-b4476.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAudpPiYnNz1LjT0QPA0KP06StCfNBPwJM',
    appId: '1:579029137093:ios:51409e1968361bd2b762ac',
    messagingSenderId: '579029137093',
    projectId: 'myinsta-b4476',
    storageBucket: 'myinsta-b4476.appspot.com',
    androidClientId: '579029137093-i1htk7lr78hjbr7u8j71jo81sck2608u.apps.googleusercontent.com',
    iosClientId: '579029137093-g8qgso62g9ipan8fqoactt739cfj1h3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myinsta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAudpPiYnNz1LjT0QPA0KP06StCfNBPwJM',
    appId: '1:579029137093:ios:51409e1968361bd2b762ac',
    messagingSenderId: '579029137093',
    projectId: 'myinsta-b4476',
    storageBucket: 'myinsta-b4476.appspot.com',
    androidClientId: '579029137093-i1htk7lr78hjbr7u8j71jo81sck2608u.apps.googleusercontent.com',
    iosClientId: '579029137093-g8qgso62g9ipan8fqoactt739cfj1h3v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myinsta',
  );
}
